services:
  db:
    image: mysql:9.4.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: blog_platform
    ports:
      - "3308:3306"
    expose:
      - 3306
